In [1]:
import pandas as pd
df = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_Won_Lost_Pct.csv")

df1 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_Scoring_Margin.csv")

df2 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_Rebound_Margin.csv")

df3 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_FG_Pct.csv")

df4 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_FT_Pct.csv")

df5 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_3FG_Pct.csv")

df6 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_OPP_FG_Pct.csv")

df7 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_OPP_3FG_Pct.csv")
df7.columns= ['Team','Opp 3FGAPG', 'Opp 3FGPG','Opp 3FG%']

df8 = pd.read_csv("./2019 csv_files/NCAA_Stats_2018-19_AST_TO_Ratio.csv")


merged_stats = df.merge(df1.merge(df2.merge(df3.merge(df4.merge(df5.merge(df6.merge(df7.merge(df8))))))))
merged_stats.head()

,Team,Games,W,L,Pct,PPG,OPP PPG,SCR MAR,RPG,OPP RPG,...,OPP FGPG,OPP FGAPG,OPP FG%,Opp 3FGAPG,Opp 3FGPG,Opp 3FG%,Rank,ASTPG,TOPG,Ratio
0,Virginia (ACC),38,35,3,92.1,71.4,56.1,15.3,34.8,29.7,...,20,53,38.5,22.32,6.45,28.9,5,14.32,9.00,1.59
1,Gonzaga (WCC),37,33,4,89.2,87.6,64.9,22.8,39.0,32.2,...,24,61,38.9,21.27,6.46,30.4,2,18.05,10.65,1.70
2,Houston (AAC),37,33,4,89.2,75.3,61.0,14.3,40.6,33.4,...,20,55,36.8,22.59,6.30,27.9,35,14.76,11.08,1.33
3,Buffalo (MAC),36,32,4,88.9,84.4,70.8,13.5,40.8,37.0,...,25,61,42.0,22.00,6.56,29.8,17,16.64,12.03,1.38
4,Wofford (SoCon),35,30,5,85.7,82.3,65.6,16.7,35.0,29.3,...,23,55,42.5,22.09,7.09,32.1,16,15.09,10.89,1.39

In [2]:
merged_stats.to_csv("./2019 csv_files/NCAA_Merged_Statistics_2018-19.csv",index = False)

In [3]:
merged_stats.insert(0,"Year",2019)
merged_stats.head()

,Year,Team,Games,W,L,Pct,PPG,OPP PPG,SCR MAR,RPG,...,OPP FGPG,OPP FGAPG,OPP FG%,Opp 3FGAPG,Opp 3FGPG,Opp 3FG%,Rank,ASTPG,TOPG,Ratio
0,2019,Virginia (ACC),38,35,3,92.1,71.4,56.1,15.3,34.8,...,20,53,38.5,22.32,6.45,28.9,5,14.32,9.00,1.59
1,2019,Gonzaga (WCC),37,33,4,89.2,87.6,64.9,22.8,39.0,...,24,61,38.9,21.27,6.46,30.4,2,18.05,10.65,1.70
2,2019,Houston (AAC),37,33,4,89.2,75.3,61.0,14.3,40.6,...,20,55,36.8,22.59,6.30,27.9,35,14.76,11.08,1.33
3,2019,Buffalo (MAC),36,32,4,88.9,84.4,70.8,13.5,40.8,...,25,61,42.0,22.00,6.56,29.8,17,16.64,12.03,1.38
4,2019,Wofford (SoCon),35,30,5,85.7,82.3,65.6,16.7,35.0,...,23,55,42.5,22.09,7.09,32.1,16,15.09,10.89,1.39

In [4]:
merged_stats.insert(2,"Power 5 School","False")
merged_stats.loc[(merged_stats['Team'].str.contains('Big 12|SEC|ACC|Big Ten|Pac-12', regex = True)),'Power 5 School'] = 'True'
merged_stats.head()

,Year,Team,Power 5 School,Games,W,L,Pct,PPG,OPP PPG,SCR MAR,...,OPP FGPG,OPP FGAPG,OPP FG%,Opp 3FGAPG,Opp 3FGPG,Opp 3FG%,Rank,ASTPG,TOPG,Ratio
0,2019,Virginia (ACC),True,38,35,3,92.1,71.4,56.1,15.3,...,20,53,38.5,22.32,6.45,28.9,5,14.32,9.00,1.59
1,2019,Gonzaga (WCC),False,37,33,4,89.2,87.6,64.9,22.8,...,24,61,38.9,21.27,6.46,30.4,2,18.05,10.65,1.70
2,2019,Houston (AAC),False,37,33,4,89.2,75.3,61.0,14.3,...,20,55,36.8,22.59,6.30,27.9,35,14.76,11.08,1.33
3,2019,Buffalo (MAC),False,36,32,4,88.9,84.4,70.8,13.5,...,25,61,42.0,22.00,6.56,29.8,17,16.64,12.03,1.38
4,2019,Wofford (SoCon),False,35,30,5,85.7,82.3,65.6,16.7,...,23,55,42.5,22.09,7.09,32.1,16,15.09,10.89,1.39

In [5]:
Large_stats = pd.read_csv("./2019 csv_files/NCAA_Entire_Statistics_2018-19.csv")
Entire_stats = Large_stats.drop(columns = ['Rank'])
Entire_stats.head()

,Year,Team,Power 5 School,Seed,Overall Seed,Berth Type,Placement,Games,W,L,...,3FG%,OPP FGPG,OPP FGAPG,OPP FG%,Opp 3FGAPG,Opp 3FGPG,Opp 3FG%,ASTPG,TOPG,Ratio
0,2019,Virginia (ACC),True,1.0,2.0,At-Large,1.0,38,35,3,...,39.5,20,53,38.5,22.32,6.45,28.9,14.32,9.00,1.59
1,2019,Gonzaga (WCC),False,1.0,4.0,At-Large,8.0,37,33,4,...,36.3,24,61,38.9,21.27,6.46,30.4,18.05,10.65,1.70
2,2019,Houston (AAC),False,3.0,9.0,At-Large,16.0,37,33,4,...,35.5,20,55,36.8,22.59,6.30,27.9,14.76,11.08,1.33
3,2019,Buffalo (MAC),False,6.0,23.0,Automatic,32.0,36,32,4,...,33.7,25,61,42.0,22.00,6.56,29.8,16.64,12.03,1.38
4,2019,Wofford (SoCon),False,7.0,28.0,Automatic,32.0,35,30,5,...,41.4,23,55,42.5,22.09,7.09,32.1,15.09,10.89,1.39

In [6]:
df[~df['Team'].isin(merged_stats['Team'])]

Empty DataFrame
Columns: [Team, Games, W, L, Pct]
Index: []